### ISSUE TITLE
Error: Cannot find module 'package-json'

### ISSUE THREAD

**Issue by eccegordo** [seawatts/ember-cli-commands#48]
Trying to install inside an addon and I get the following error when install via ember command

› node -v
v6.7.0

```
› ember install ember-cli-commands
NPM: Installed ember-cli-commands
Cannot find module 'package-json'
Error: Cannot find module 'package-json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...snip snip ... /node_modules/ember-cli-commands/lib/utils/get-ember-cli-tags.js:1:83)
    at Module._compile (module.js:556:32)

```

**Comment by eccegordo** [comment]
I was able to go inside `node_modules/ember-cli-commands` and manually run npm install there. That seemed to fix the package-json error.

But then when I run the upgrade command it doesn't seem to actually do anything.

Either way I think there something not getting installed completely.

My environment with a real world app

› ember -v
ember-cli: 2.12.1
node: 6.7.0
os: darwin x64

**Comment by seawatts** [comment]
Good catch. Looks like there are a couple dependencies I need to declare in dependencies instead of devDependencies

**Comment by seawatts** [comment]
Should be fixed in https://github.com/seawatts/ember-cli-commands/commit/daac732f4bbd7a13f77910bd196b6b2fe8a6d047 @eccegordo can you confirm?

**Comment by eccegordo** [comment]
installed a copy of the develop branch and it seems to work now. Also noticed that you used new ember addon output too. Good catch. Looking pretty good.

I updated an old addon from "ember-cli": "0.2.7", all the way to 2.12.1 easy!
