### ISSUE TITLE
Log to UI when fetching ember-new-output

### ISSUE THREAD

**Issue by eccegordo** [seawatts/ember-cli-commands#50]
https://github.com/seawatts/ember-cli-commands/blob/develop/lib/utils/fetch-ember-new-output.js#L4

It might be a good idea to log or console out this to UI. For two reasons

1.) Makes it obvious to the user what happens behind the scenes. Show the exact URL fetched so user can look at it themselves.
2.) If a network issue or some janky network connection causes problems it is clear what was attempted but failed. Although I see you have a catch inside the `fetchJSON` promise that does a console.log so that might be sufficient.

**Comment by seawatts** [comment]
This should be available now by passing in `--verbose`

**Comment by eccegordo** [comment]
confirm
